dataset_params: 
  data: Ising
  classes: [0,1]
  img_size: 16
  
training_params:
  num_epochs: 100
  n_data: Null
  batchsize: 128 
  loss_type: [BCE_loss, accuracy]
  
model_params:  
  model_type: quantum_classifier
  num_wires: 8
  equiv: False
  trans_inv : True
  hybrid: False
  ver: U_SO4
  delta: 0.1
  

opt_params: 
  lr: 0.01
  b1: 0.5
  b2: 0.999
  
logging_params: 
  save_dir: test